site_name: .
site_name: .

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: slate   # Enforces dark mode
    primary: teal
    accent: light-blue
  logo: assets/image.png
  favicon: assets/favicon.ico

  logo: assets/image.png


  # Add a custom vibrant logo here

nav:
  - Docs: index.md
  - Core:
      - Machine Learning:
          - Supervised:
              - Classification: 
                  - base: api/core/ml/supervised/classification/base.md
                  - naive bayes: api/core/ml/supervised/classification/naive_bayes.md
                  - Logistic regression: api/core/ml/supervised/classification/logistic_regression.md
                  - Decision tree: api/core/ml/supervised/classification/decision_tree.md
                  - SVM: api/core/ml/supervised/classification/svm.md
              - Regression:
                  - base: api/core/ml/supervised/regression/base.md
                  - Linear regression: api/core/ml/supervised/regression/linear_regression.md
                  - Ridge regression: api/core/ml/supervised/regression/ridge_regression.md
                  - Lasso regression: api/core/ml/supervised/regression/lasso_regression.md
                  - Polynomial regression: api/core/ml/supervised/regression/polynomial_regression.md
                  - support vector regression: api/core/ml/supervised/regression/svr.md

          - Unsupervised:
              - Clustering: 
                  - Base: api/core/ml/unsupervised/clustering/base.md
                  - Kmeans: api/core/ml/unsupervised/clustering/kmeans.md
                  - Agglomerative: api/core/ml/unsupervised/clustering/agglomerative.md
                  - GMM: api/core/ml/unsupervised/clustering/gmm.md
                  - Hdbscan: api/core/ml/unsupervised/clustering/hdbscan.md
                  - Dbscan: api/core/ml/unsupervised/clustering/dbscan.md
                  - Optics: api/core/ml/unsupervised/clustering/optics.md
      - Deep Learning: 
          - NN :
            - activation: api/core/dl/nn/activation.md
            - loss: api/core/dl/nn/loss.md
            - metrics: api/core/dl/nn/metrics.md
            - others: api/core/dl/nn/others.md
          - Layer :
            - attention : api/core/dl/layer/attention.md
            - convolution : api/core/dl/layer/convolution.md
            - dropout : api/core/dl/layer/dropout.md
            - embeddings : api/core/dl/layer/embeddings.md
            - linear : api/core/dl/layer/linear.md
            - normalisation : api/core/dl/layer/normalisation.md
            - pooling : api/core/dl/layer/pooling.md
            - recurrent : api/core/dl/layer/recurrent.md
            - sequential : api/core/dl/layer/sequential.md
          - tensorflow_wrapper: api/core/dl/tensorflow_wrapper.md
          - fcnn: api/core/dl/fcnn.md
          - gcn: api/core/dl/gcn.md
          - base: api/core/dl/base.md
          - MLP: api/core/dl/mlp.md
      - SciML:
          - PINNS:
            - Model:
              - Model: api/core/sciml/pinns/model/model.md
            - Physics: 
              - cd2d: api/core/sciml/pinns/physics/cd2d.md
              - Poisson2d: api/core/sciml/pinns/physics/poisson2d.md  
          - FNO:
            - Layer:
              - FNO block: api/core/sciml/fno/layers/fno_block_1d.md 
              - Spectral conv: api/core/sciml/fno/layers/spectral_conv_1d.md
            - Models: 
              - FNO: api/core/sciml/fno/layers/fno_1d.md        
          - Geometry:
              - geometry_2d: api/core/sciml/geometry/geometry_2d.md
              - geometry: api/core/sciml/geometry/geometry.md
          - fe:
              - Chebyshev: api/core/sciml/fe/basis_2d_QN_Chebyshev_2.md
              - jacobi: api/core/sciml/fe/basis_2d_QN_Jacobi.md 
              - Legendre_Special: api/core/sciml/fe/basis_2d_QN_Legendre_Special.md
              - Legendre: api/core/sciml/fe/basis_2d_QN_Legendre.md
              - Function 2D: api/core/sciml/fe/basis_function_2d.md
              - Function 3D: api/core/sciml/fe/basis_function_3d.md
              - FE_transformation_2d: api/core/sciml/fe/fe_transformation_2d.md
              - FE_transformation_3d: api/core/sciml/fe/fe_transformation_3d.md
              - FE2D_Cell: api/core/sciml/fe/fe2d_cell.md
              - fe2d_setup_main: api/core/sciml/fe/fe2d_setup_main.md
              - fespace: api/core/sciml/fe/fespace.md
              - fespace2d: api/core/sciml/fe/fespace2d.md
              - quad_affine: api/core/sciml/fe/quad_affine.md
              - quad_bilinear: api/core/sciml/fe/quad_bilinear.md
              - quadratureformulas_quad2d: api/core/sciml/fe/quadratureformulas_quad2d.md
              - quadratureformulas: api/core/sciml/fe/quadratureformulas.md    
          - fastvpinns:
            - data:
              - datahandler: api/core/sciml/fastvpinns/data/datahandler.md
              - datahandler2: api/core/sciml/fastvpinns/data/datahandler2d.md
            - Model:
              - Model hard : api/core/sciml/fastvpinns/model/model_hard.md
              - Model inverse domain: api/core/sciml/fastvpinns/model/model_inverse_domain.md
              - Model inverse : api/core/sciml/fastvpinns/model/model_inverse.md
              - Model  : api/core/sciml/fastvpinns/model/model.md
            - Physics:
              - cd2d_inverse_domain : api/core/sciml/fastvpinns/physics/cd2d_inverse_domain.md
              - cd2d_inverse: api/core/sciml/fastvpinns/physics/cd2d_inverse.md
              - cd2d: api/core/sciml/fastvpinns/physics/cd2d.md
              - helmholtz2d: api/core/sciml/fastvpinns/physics/helmholtz2d.md
              - poisson2d:  api/core/sciml/fastvpinns/physics/poisson2d.md
              - poissson2d Inverse :   api/core/sciml/fastvpinns/physics/poisson_2d_inverse.md 
      - Model compression:
          - pruning: api/core/model_compression/pruning.md
          - quantization: api/core/model_compression/quantization.md
  - Examples:
        - ML:
          - superivised :
             - classification:
               - example logistic regresssion: api/core/examples/ml/supervised/classification/example_logistic_regression.md
               - example naive bayes: api/core/examples/ml/supervised/classification/example_naive_bayes.md
             - regression:
                - example linear regression: api/core/examples/ml/supervised/regression/example_linear_regression.md
                - example ridge regression: api/core/examples/ml/supervised/regression/example_ridge_regression.md
                - example lasso regression: api/core/examples/ml/supervised/regression/example_lasso_regression.md  
                - example polynomial regression: api/core/examples/ml/supervised/regression/example_polynomial_regression.md
                - example support vector regression: api/core/examples/ml/supervised/regression/example_svr.md
          - unsupervised :
             - clustering:
               - example Kmeans: api/core/examples/ml/unsupervised/clustering/example_naive_bayes.md
        - DL:
          - cnn_mnist : api/core/examples/dl/cnn_mnist.md
          - vae_mnist : api/core/examples/dl/vae_mnist.md
          - gcn_cora : api/core/examples/dl/gcn_cora.md
        - Model compression:
          - pruned base mnist: api/core/examples/model compression/pruned_base_mnist.md
          - pruned mnist: api/core/examples/model compression/pruned_mnist.md
          - quantized base mnist: api/core/examples/model compression/quantized_base_mnist.md
          - quantized mnist: api/core/examples/model compression/quantized_mnist.md
        - Sciml:
          - Fastvpinns:
             - example helmhotlz2d: api/core/examples/sciml/fastvpinns/example_helmholtz2d.md
             - example poisson2d: api/core/examples/sciml/fastvpinns/example_poisson2d.md
          - FNO:
             - example_advection: api/core/examples/sciml/fno/example_advection.md 
             - example_burgers: api/core/examples/sciml/fno/example_burgers.md 
             - example_heat: api/core/examples/sciml/fno/example_heat.md 
             - example_wave: api/core/examples/sciml/fno/example_wave.md 
          - PINNs   :
             - example_poisson2d: api/core/examples/sciml/pinns/forwardproblems/example_poisson2d.md
  - Contribution:
          - contribution: api/core/Contribution/contribution.md         
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
 # - pymdownx.emoji:
 #     emoji_index: !!python/name:materialx.emoji.twemoji
 #     emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [".", "scirex", "examples"]
          options:
            rendering:
              show_source: true
              
  - search:
      lang: en
      #separator: "[/s/-]+"

extra_css:
  - assets/custom.css  # Custom vibrant colors

extra_picture:
  - assets/binary-bg.png

extra_javascript:
  - assets/custom.js  # Advanced interactivity like smooth scrolling or dynamic effects
